name: Waka - Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 08:00 Asia/Shanghai

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: Hazel-Lin/Hazel-Lin
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          TIME_RANGE: last_30_days
          LANG_COUNT: 8
          SHOW_TIME: true
          SHOW_TOTAL: false
          SHOW_MASKED_TIME: true
          STOP_AT_OTHER: false
          IGNORED_LANGUAGES: Markdown JSON "Git Config" Text TOML YAML XML CSV TSV
